server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://api.asgardeo.io/t/bprocess/oauth2/jwks
          issuer-uri: https://api.asgardeo.io/t/bprocess/oauth2/token

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2.jwt: TRACE