server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.asgardeo.io/t/bprocess   # 👈 switch to issuer

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    com.nimbusds.jose: TRACE
    com.nimbusds.jose.proc: TRACE
    com.nimbusds.jose.jwk.source: TRACE
    org.springframework.web.client.RestTemplate: DEBUG